apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: stox
  labels:
    app: inventory-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      serviceAccountName: inventory-service-account
      containers:
      - name: inventory-service
        image: inventory-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: PROJECT_NAME
          valueFrom:
            configMapKeyRef:
              name: inventory-config
              key: PROJECT_NAME
        - name: PROJECT_VERSION
          valueFrom:
            configMapKeyRef:
              name: inventory-config
              key: PROJECT_VERSION
        - name: PROJECT_DESCRIPTION
          valueFrom:
            configMapKeyRef:
              name: inventory-config
              key: PROJECT_DESCRIPTION
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: inventory-secrets
              key: JWT_SECRET_KEY
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: inventory-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: inventory-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: inventory-config
              key: POSTGRES_DB
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: inventory-config
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: inventory-config
              key: POSTGRES_PORT
        - name: AUTH_SERVICE_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: inventory-config
              key: AUTH_SERVICE_BASE_URL
        - name: INVENTORY_SERVICE_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: inventory-config
              key: INVENTORY_SERVICE_BASE_URL
        - name: ORDER_SERVICE_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: inventory-config
              key: ORDER_SERVICE_BASE_URL
        livenessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 60