apiVersion: v1
kind: PersistentVolume
metadata:
  name: inventory-db-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lib/storage/inventory-db
  storageClassName: standard