apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: inventory-db
  namespace: stox
  labels:
    app: inventory-db
spec:
  serviceName: "inventory-db"
  replicas: 1
  selector:
    matchLabels:
      app: inventory-db
  template:
    metadata:
      labels:
        app: inventory-db
    spec:
      serviceAccountName: inventory-service-account 
      securityContext:
        fsGroup: 999
      containers:
      - name: inventory-db
        image: inventory-db:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 999
          runAsGroup: 999
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: inventory-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: inventory-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: inventory-config
              key: POSTGRES_DB
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: inventory-db
        livenessProbe:
          exec:
            command:
            - "/bin/sh"
            - "-c"
            - "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - "/bin/sh"
            - "-c"
            - "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"
          initialDelaySeconds: 30
          periodSeconds: 30
      volumes:
      - name: inventory-db
        persistentVolumeClaim:
          claimName: inventory-db-pvc