apiVersion: v1
kind: Service
metadata:
  name: inventory-db
spec:
  selector:
    app: inventory-db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  clusterIP: None # Headless service for direct communication